name: Generate Sensor Docs

on:
  workflow_call:
    secrets:
      SENSOR_TOKEN:
        required: true

permissions:
  contents: write

jobs:
  build-docs:
    runs-on: ubuntu-latest
    env:
      SENSOR_TOKEN: ${{ secrets.SENSOR_TOKEN }}

    steps:
      - name: 📥 Checkout Repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.SENSOR_TOKEN }}

      - name: 🔧 Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: 📦 Install Dependencies
        run: pip install requests

      - name: 📚 Generate Markdown Files
        run: python .github/scripts/generate_sensor_docs.py

      - name: ✅ Commit Generated Docs using SENSOR_TOKEN
        run: |
          git config --global user.name "sensor-bot"
          git config --global user.email "sensor-bot@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${SENSOR_TOKEN}@github.com/${{ github.repository }}
          git add docs/sensors/
          git diff --cached --quiet || git commit -m "📚 Updated sensor docs from latest scrape"
          git pull --rebase origin main
          git push origin HEAD:${GITHUB_REF##refs/heads/}
