name: Scrape Sensors

on:
  workflow_call:
    secrets:
      SENSOR_TOKEN:
        required: true

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    env:
      SENSOR_TOKEN: ${{ secrets.SENSOR_TOKEN }}

    steps:
      - name: 📥 Checkout Repo
        uses: actions/checkout@v3

      - name: 🔧 Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: 📦 Install Dependencies
        run: pip install requests beautifulsoup4

      - name: 🛠 Scrape Choovio Sensors
        run: python .github/scripts/scrape_choovio_daily.py

      - name: 🚀 Commit Scraped Data
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data_sensors.json scraped_urls.txt
          git diff --cached --quiet || git commit -m "🔄 Daily Choovio scrape update"
          git push
